version: "3.8"

services:
  elastic:
    image: elasticsearch:8.11.1
    restart: always
    container_name: sc_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - 9200:9200
  postgres:
    image: postgres:14
    restart: always
    container_name: sc_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432 

